### PR TITLE
Version 1.19.3

### PR DESCRIPTION
**Pull request by lapineige**
https://framagit.org/les/gancio/-/releases/v1.19.3

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Why does that log folder creation fails ? :thinking:

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Let's merge ? :)

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
