### PR TITLE
Initial version (1.6.17)

### PR DESCRIPTION
**Pull request by lapineige**
https://framagit.org/les/gancio/-/releases/v1.6.17

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
#3 should clean up the remaining issues

**Comment by lapineige** [comment]
Oh, I didn't see you comment before committing.
Thank you for all that work.

**Comment by lapineige** [comment]
!testme

**Pull request merged**
