### PR TITLE
v1.15 + admin password + screenshot + autoupdate + github templates

### PR DESCRIPTION
**Pull request by lapineige**
Complete admin account creation.

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
`Use either `nuxt build --modern` or `modern` option to build modern `

:thinking:

@lesion do you have an idea of why this error appears with this new version ? I don't see a dependency change on Gancio side :thinking:

**Comment by lapineige** [comment]
!testme

**Comment by lesion** [comment]
> `` Use either `nuxt build --modern` or `modern` option to build modern ``
> 
> 🤔
> 
> @lesion do you have an idea of why this error appears with this new version ? I don't see a dependency change on Gancio side 🤔

I had missed this comment, I will try to run the test locally to debug

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
> 84060 INFO DEBUG - sudo: nuxt: command not found

@lesion should I install nuxt ?
Should it be run with NPM, NODE, YARN ? :thinking:

**Comment by lapineige** [comment]
!testme

**Comment by kamazeuci** [comment]
Is there a way I could help with this? (I'm no programmer but can work my way in gnu/linux).thanks.

**Comment by lapineige** [comment]
> also, we should upgrade to nodejs 18 and to the last release (1.15.5)

Let's try to work on it there ? https://github.com/YunoHost-Apps/gancio_ynh/pull/10

**Comment by lesion** [comment]
The issue here is that there is no `nuxt build` command, specify that command in `package.json` is not the same as running in a shell and should not be used because you will never know where your package manager will install the binary.
I would strongly suggest to reproduce the [installation instructions](https://gancio.org/install/debian)

**Comment by lapineige** [comment]
Testers needed :smiley:

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
So I'm going to merge it, but feedback are still wanted to know if it finally works as expected :)

**Comment by kamazeuci** [comment]
I upgraded the gancio yunohost app to the new version but still can't login nor register a new user... maybe I should make a clean install?

**Comment by lesion** [comment]
> ok, I made a clean install but still can't login/register a user....

could you try to register a new user?

**Comment by kamazeuci** [comment]
> > ok, I made a clean install but still can't login/register a user....
> 
> could you try to register a new user? in case you can't, what's the error? thx

I don't receive the email. But that might have to do with the SMTP relay not properly configured. Do you know how to configure a SMTP relay on gancio? I've looked in documentation but found nothing

**Comment by lesion** [comment]
> > > ok, I made a clean install but still can't login/register a user....
> > 
> > 
> > could you try to register a new user? in case you can't, what's the error? thx
> 
> I don't receive the email. But that might have to do with the SMTP relay not properly configured. Do you know how to configure a SMTP relay on gancio? I've looked in documentation but found nothing

Note that the first registered use will be an active administrator so there is no need of email confirmation.
Then you can login with your admin credential and manage users, SMTP settings, etc..

**Comment by kamazeuci** [comment]
it worked!!
thanks a lot!!

**Comment by kamazeuci** [comment]
I am in (sometimes it lets me in, sometimes not, I have no idea why)
as an admin
and I can create new users... but these new users need to receive the confirmation email... and the confirmation email is not being sent/received... where can I configure SMTP relay settings?

**Comment by kamazeuci** [comment]
Just found options on the web gui! for email config. will try that. thanks!!

**Pull request merged**
