### PR TITLE
Multiinstance

### LINKED ISSUE #25: app can't be installed more than once
I was about to install gancio on another domain, for another project(because I loved the experience on my first one) but YNH says it can only be installed once :-(
Why is this? is this temporal? is there a workaround?

thanks

### PR DESCRIPTION
**Pull request by lapineige**
Fix #25

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
ping @kamazeuci

**Comment by kamazeuci** [comment]
Cool!! Thanks to everybody. I'm so happy this community is so helpful.
Can I help with something? Or just wait for the update to be available? (I'm sorry I'm a beginner in git and ynh, although I do want to learn to package an app)
Thanks!

**Comment by lapineige** [comment]
You can try to (multi) install this branch: `yunohost app install https://github.com/YunoHost-Apps/gancio_ynh/tree/multiinstance`
(first upgrade your current instance with `yunohost app upgrade gancio -u https://github.com/YunoHost-Apps/gancio_ynh/tree/multiinstance`)

And report if everything work well :)

**Comment by kamazeuci** [comment]
ok thanks! I will try that.. just one question, after this goes into main, I will have to revert the versions back to main? or that will happen automatically?

**Comment by lapineige** [comment]
Yunohost will check the latest version (number) available on the main branch.
If that version is higher ("newer") than the current one, it will allow you to upgrade to it.
So until the main branch is more up-to-date that the testing one (or any custom branch), no update will be shown. And then you will switch on the main branch without any particular action.

As both are compatible, there is no issue. There could be one if the version in the custom branch could not be switched straightaway to the main branch. That's not the case :)

**Comment by lapineige** [comment]
It depends :)

If you can't afford any shutdown : no.

If you can afford a downtime while doing the upgrade, test, and maybe revert to a backup (the one made before the upgrade), then maybe. Of course it's not 100% guaranteed to work without any issue.

**Comment by kamazeuci** [comment]
I am sorry I am taking a while. I am waiting for a moment in which I could try this and afford to have a few hours of downtime of my first gancio instance... that has to be in the deep night... so I'll do my best to try it this month. Thanks to everybody.

**Comment by lapineige** [comment]
Nobody is in an hurry, take the time you need :)

**Comment by kamazeuci** [comment]
Ok. Done! Everything went smooth as silk. Now I have the two instances going, multiinstance is working fine!

Guess a next step would be updating gancio_ynh as the upstream gancio is already at  1.19.0 (2024-08-21) and it has a bunch of interesting features!
thanks!!!!!

**Pull request merged**
